name: build

on: [push, pull_request]

jobs:
  build_and_upload:
    name: build
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, release_uname: "linux-x86_64" }
          #- { os: macos-latest, release_uname: "mac" }
          - { os: windows-latest, release_uname: "windows" }

    steps:
      - uses: actions/checkout@v1
      - name: nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: ubuntu
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libsqlcipher0 libsqlcipher-dev
          cargo install cargo-deb

      - name: build
        run: |
          npm install
          npm run lint
          npm run build