name: mac

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: build
        run: |
          brew install sqlcipher
          export SQLCIPHER_STATIC=1
          export SQLCIPHER_LIB_DIR=/usr/local/opt/sqlcipher/lib
          export SQLCIPHER_INCLUDE_DIR=/usr/local/opt/sqlcipher/include
          npm install
          npm run build:cargo
          otool -L target/debug/radical-native